material: STICK
regex:
  no-one-claimed-block: '"text":"No one has claimed this block\."}'
  size: '  [0-9]+x[0-9]+\=[0-9]+'
  last-login: '  Last login: [0-9]+ days ago.'
  claimed-by: '"text":"That block has been claimed by(.*)\.'